language: node_js
node_js:
  - 'node'

branches:
  only:
    - master

jobs:
  include:
    - stage: 'Lint'
      name: 'Prettier'
      script: yarn lint:prettier
    - script: yarn lint:tslint && yarn lint:tsc
      name: 'TypeScript'
    - stage: 'Tests'
      name: 'Unit Tests'
      script: yarn test:coverage && cat ./coverage/lcov.info | node_modules/.bin/coveralls --verbose
    - stage: 'Build'
      name: 'Package'
      script: yarn build
    - script: rm -rf ./node_modules && cd ./examples && yarn && yarn build
      name: 'Examples'
